In [1]:
import pandas as pd
import datetime
df = pd.read_csv('Europe Sales Records.csv')
#Task 1 Dataset overview
#total number of rows and columns
df.shape

(1330, 14)

In [2]:
#Name od all columns
df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [4]:
#datatypes of each columns
df.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [5]:
#missing values
df.isnull()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1326,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1327,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1328,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1329,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
#to check duplicates
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1325    False
1326    False
1327    False
1328    False
1329    False
Length: 1330, dtype: bool

In [7]:
#dropping duplicates
df.drop_duplicates(inplace=True)

In [8]:
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,4/14/2014,559183347,5/21/2014,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,11/9/2015,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,5/9/2012,713357150,6/3/2012,7088,109.28,35.84,774576.64,254033.92,520542.72
1329,Europe,Finland,Clothes,Online,L,4/22/2014,906794202,5/11/2014,9410,109.28,35.84,1028324.80,337254.40,691070.40

In [9]:
#total revenue generated by each country
total_revenue= df.groupby('Country')['Total Revenue'].sum()
print(total_revenue)

Country
Albania                   32224853.87
Andorra                   47756693.17
Armenia                   37519840.21
Austria                   35740871.49
Belarus                   34236260.77
Belgium                   25852572.30
Bosnia and Herzegovina    50117508.49
Bulgaria                  38161555.70
Croatia                   27348195.70
Cyprus                    33008851.50
Czech Republic            53543932.14
Denmark                   26968532.52
Estonia                   23410001.79
Finland                   26027948.98
France                    39362112.15
Georgia                   22802195.66
Germany                   38055087.56
Greece                    38699541.70
Hungary                   42408249.12
Iceland                   25570227.40
Ireland                   33022223.31
Italy                     35878352.12
Kosovo                    53833142.79
Latvia                    38722084.15
Liechtenstein             29872564.41
Lithuania                 29031942.10
Luxembourg                33075377.21
Macedonia                 49222085.25
Malta                     47145320.81
Moldova                   27031700.06
Monaco                    13828738.16
Montenegro                31346476.90
Netherlands               20860788.79
Norway                    31520698.50
Poland                    33805403.22
Portugal                  47172189.84
Romania                   34286150.85
Russia                    46051659.81
San Marino                47883708.48
Serbia                    42193537.74
Slovakia                  42940998.32
Slovenia                  38892531.27
Spain                     27644278.67
Sweden                    35482128.02
Switzerland               31875174.00
Ukraine                   53252317.54
United Kingdom            26654989.47
Vatican City              22280804.10
Name: Total Revenue, dtype: float64

In [10]:
#top 10 highest revenue country
print(total_revenue.sort_values(ascending=False).head(10))

Country
Kosovo                    53833142.79
Czech Republic            53543932.14
Ukraine                   53252317.54
Bosnia and Herzegovina    50117508.49
Macedonia                 49222085.25
San Marino                47883708.48
Andorra                   47756693.17
Portugal                  47172189.84
Malta                     47145320.81
Russia                    46051659.81
Name: Total Revenue, dtype: float64

In [11]:
#total profit genertaed by each country
total_profit = df.groupby('Country')['Total Profit'].sum()
print(total_profit)

Country
Albania                   10490706.02
Andorra                   15410036.63
Armenia                    9422353.18
Austria                   10027509.64
Belarus                   11852421.05
Belgium                    7476060.14
Bosnia and Herzegovina    13257602.77
Bulgaria                  10408342.61
Croatia                    7388447.57
Cyprus                    10032220.56
Czech Republic            13635593.78
Denmark                    9617418.06
Estonia                    7828593.56
Finland                    7525362.83
France                    10842345.66
Georgia                    5697679.21
Germany                   11582919.10
Greece                    12324450.13
Hungary                   13786231.03
Iceland                    7278112.15
Ireland                    9830365.71
Italy                     10913921.97
Kosovo                    14409145.45
Latvia                    10759285.29
Liechtenstein              8397411.11
Lithuania                  7997297.83
Luxembourg                 9870766.11
Macedonia                 13684099.95
Malta                     14610127.88
Moldova                    6902456.08
Monaco                     4797048.77
Montenegro                11169660.56
Netherlands                5762490.70
Norway                     9875771.81
Poland                    10671100.99
Portugal                  11345407.59
Romania                   10793548.69
Russia                    13267682.64
San Marino                13792992.81
Serbia                    11853514.38
Slovakia                  12052790.03
Slovenia                  12123524.52
Spain                      8173545.22
Sweden                    11155328.59
Switzerland               11037297.60
Ukraine                   14804925.74
United Kingdom             9326312.21
Vatican City               6413822.41
Name: Total Profit, dtype: float64

In [46]:
#top 5 countries with highest profit
print(total_profit.sort_values(ascending=False).head(5))

Country
Andorra       15410036.63
Ukraine       14804925.74
Malta         14610127.88
Kosovo        14409145.45
San Marino    13792992.81
Name: Total Profit, dtype: float64

In [47]:
#top 5 countries having lowest profit
print(total_profit.sort_values(ascending=False).tail(5))

Country
Moldova         6902456.08
Vatican City    6413822.41
Netherlands     5762490.70
Georgia         5697679.21
Monaco          4797048.77
Name: Total Profit, dtype: float64

In [48]:
#toal units sold per item type
unit_sold_itype= df.groupby('Item Type')['Units Sold'].sum()
print(unit_sold_itype)

Item Type
Baby Food          562706
Beverages          613133
Cereal             465685
Clothes            591385
Cosmetics          533291
Fruits             591672
Household          440249
Meat               533376
Office Supplies    617641
Personal Care      560480
Snacks             490160
Vegetables         582544
Name: Units Sold, dtype: int64

In [49]:
# item type which is sold the maximum
print(unit_sold_itype.sort_values(ascending=False).head(1))

Item Type
Office Supplies    617641
Name: Units Sold, dtype: int64

In [70]:
#total profit per item type
total_profit_itype= df.groupby('Item Type')['Total Profit'].sum()
print(total_profit_itype.sort_values(ascending=False).head(1))

Item Type
Cosmetics    92723306.17
Name: Total Profit, dtype: float64

In [71]:
#total revenue per sales channe;
total_revenue = df.groupby('Sales Channel')['Total Revenue'].sum()
print(total_revenue)

Sales Channel
Offline    8.732536e+08
Online     8.303688e+08
Name: Total Revenue, dtype: float64

In [72]:
#total profit per sales channel
total_profit_channel = df.groupby('Sales Channel')['Total Profit'].sum()
print(total_profit_channel)

Sales Channel
Offline    2.537081e+08
Online     2.479679e+08
Name: Total Profit, dtype: float64

In [73]:
# best sales channel
best_channel = total_profit_channel.head(1)
print(best_channel)

Sales Channel
Offline    2.537081e+08
Name: Total Profit, dtype: float64

In [74]:
#order count
count_of_order = df['Order Priority'].value_counts()
print(count_of_order)

Order Priority
M    354
H    335
L    334
C    307
Name: count, dtype: int64

In [75]:
# average profit per order priority
avg_profit = df.groupby('Order Priority')['Total Profit'].mean()
print(avg_profit)

Order Priority
C    395873.863941
H    383001.165672
L    343937.392096
M    386899.131723
Name: Total Profit, dtype: float64

In [76]:
print(avg_profit.head(1))

Order Priority
C    395873.863941
Name: Total Profit, dtype: float64

In [77]:
#correlation between total revenue and total profit
correlation = df['Total Revenue'].corr(df['Total Profit'])
print(correlation)

0.8739605151424565

In [78]:
#check  whether highest profit generates high revenue
check = df.groupby('Total Revenue')['Total Profit'].mean()
print(check)
print(check.sort_values(ascending=False).head(1))

Total Revenue
503.82            130.14
1044.96           269.92
1302.42           252.50
1336.54           331.46
2929.62           756.74
                 ...
6359716.86    1232957.50
6468853.60    1604266.40
6483446.76    1256945.00
6510146.37    1262121.25
6672675.95    1654814.05
Name: Total Profit, Length: 1323, dtype: float64
Total Revenue
4275816.0    1700448.6
Name: Total Profit, dtype: float64

In [79]:
#conversion of order id date to datetime format using datetime module
convert_order_date= pd.to_datetime(df['Order Date'])
print(convert_order_date)

0      2011-09-12
1      2013-10-14
2      2014-08-13
3      2010-10-31
4      2016-09-28
          ...
1325   2014-01-14
1326   2014-04-14
1327   2015-11-09
1328   2012-05-09
1329   2014-04-22
Name: Order Date, Length: 1330, dtype: datetime64[ns]

In [80]:
#total revenue of each month
total_revenue_month = df.groupby(convert_order_date.dt.month)['Total Revenue'].sum()
print(total_revenue_month)

Order Date
1     1.579039e+08
2     1.415449e+08
3     1.706923e+08
4     1.148074e+08
5     1.577288e+08
6     1.660835e+08
7     1.559474e+08
8     1.172059e+08
9     1.273245e+08
10    1.078330e+08
11    1.394554e+08
12    1.470954e+08
Name: Total Revenue, dtype: float64

In [81]:
#number of the month that generated highest revenue
print(total_revenue_month.sort_values(ascending=False).head(1))

Order Date
3    1.706923e+08
Name: Total Revenue, dtype: float64

In [82]:
#number of the month generated lowest revenue
print(total_revenue_month.sort_values(ascending=False).tail(1))

Order Date
10    1.078330e+08
Name: Total Revenue, dtype: float64

In [83]:
#business summary report having total revenue,total profit,best perofrming country best selling item type total order processed and best sales channels
print("Total Revenue:", df['Total Revenue'].sum())
print("Total Profit:", df['Total Profit'].sum())
print("Best Performing Country:", total_revenue.sort_values(ascending=False).head(1).index[0])
print("Best Selling Item Type:",unit_sold_itype.sort_values(ascending=False).head(1))
print("Total Order Processed:", df['Order ID'].nunique())
print("Best Sales Channel:",best_channel)

Total Revenue: 1703622398.11
Total Profit: 501676048.32000005
Best Performing Country: Offline
Best Selling Item Type: Item Type
Office Supplies    617641
Name: Units Sold, dtype: int64
Total Order Processed: 1330
Best Sales Channel: Sales Channel
Offline    2.537081e+08
Name: Total Profit, dtype: float64